import Head from "next/head";

export type MetaProps = {
  pageTitle: string;
};

export default function PageMeta(props: MetaProps) {
  return (
    <Head>
      <title>{`${props.pageTitle}`}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
